### ISSUE TITLE
List of current issues as of 05/18/17

### ISSUE THREAD

**Issue by maxim-fedotov-1997** [shardick/trucky-companion-app#5]
Hello there! I like this app and I'm also very excited to maybe offer help on reporting current bugs and issues this app has.
1) Steam integration seems to be unfinished? I get "Connected!" when I log into my account, but this doesn't changes anything. I can't look at friends list, for example. ![screenshot 1](https://cloud.githubusercontent.com/assets/5875717/26198472/53542582-3bf0-11e7-8c3f-f9d20e80657b.png)
2) Live map doesn't loads, oddly. Also, back button on screen seems to not react, which makes me use back button of phone itself.
3) "Search player" menu is only able to work around with TruckersMP ID used, when looking for Steam ID or name, it returns "No player found". And then even if it does finds me with TMP ID, it fails to match it with right Steam profile, resulting in someone's other profile being shown, which isn't mine. ![picture 2](https://cloud.githubusercontent.com/assets/5875717/26198474/535909f8-3bf0-11e7-92e9-a793dbbe9659.png)
4) When in main menu, phone's back button backs me into non ending splash? I think there should be an working exit call when it's performed. ![screenshot 3](https://cloud.githubusercontent.com/assets/5875717/26198473/53550678-3bf0-11e7-8f3d-314ac035cf21.png)
That is all I've got to say on the issues. Solid 4 to your app for what it does, but with fixed bugs, I'll be more than happy to give it 5.
Have a good day!

**Comment by shardick** [comment]
Hi @maxim-fedotov-1997 ,
thanks for the report.
Very helpful.

Can you provide some data to test? like user id, steam id, device, android version to try to reproduce?

**Comment by maxim-fedotov-1997** [comment]
TMP ID: 9858
Steam ID: fire_sparkle_rus
Device: Android, Lenovo A526 version 4.2.2
And ya' welcome. I'm very interested in helping you out, as TruckApp is getting sorta boring with only server info and meetups. :D

**Comment by shardick** [comment]
Uh, Android 4.2.2 . this might to be a problem :)

**Comment by maxim-fedotov-1997** [comment]
Ah, thought so. My phone is ancient enough, plus it refuses to find any updates. Like, "nope, you are on the last version". Noted. :)

**Comment by shardick** [comment]
Hi @maxim-fedotov-1997 ,
version 1.0.7 (already live on play store) fix search player bug and navigation bug on splash screen. For other two bugs, unfortunately, i've tested on emulator 4.2.2 and cannot reproduce the bugs, steam auth and live map work correctly.

**Comment by maxim-fedotov-1997** [comment]
Gonna try on tablet... Reporting back in somewhere 1 hour...

**Comment by maxim-fedotov-1997** [comment]
Got the results. Even tested on the device of my father too. So, the results...
1) Lenovo IdeaTab S6000-H, Android 4.2.2:
Still has same problems with map and Steam login. Plus, I found out something more... (screenshot attached)
Could that be made less big, like Steam app does it when on tablet?
2) ZTE Blade A465, Android 5.1:
Both functions managed to work and they did not had any other problem.
Outputting you processors of all devices, just in case:
1) Lenovo A526 - ARMv7 rev 3 (v7l) @1300Mhz (Quad core)
2) Lenovo IdeaTab S6000-H - ARMv7 rev 2 (v7l) @1209Mhz (Quad core)
3) ZTE Blade A465 - AArch64 rev 4 (aarch64) @988Mhz (Quad core)
And it's surely not my internet, as I managed to get it working on ZTE phone even with sh**ty internet XD
Maybe put up text "Might not work if your device has Android 4.x" if it can't be fixed...
So, there ya' go... Should be enough. Waiting on your reply. :)

**Comment by shardick** [comment]
Sorry, don't see the screenshot, can you resend please?

**Comment by shardick** [comment]
I see, thank you.

Understood, app drawer is too big, indeed. Maybe can reduce to 30-40% of screen when on tablet. I'll try on emulator.

Would you try something deeper? You can link your 4.2.2 device and see what the app logs debugging with adb logcat ? It's a mess that don't work on 4.2 , but i don't have devices to debug on :(

**Comment by maxim-fedotov-1997** [comment]
Also might be processors, that I had a second thought...
But lets try that. I'll do it after weekend, though, as Sundays are veery busy with university... Will report back once I get some results. Cheers!

**Comment by shardick** [comment]
I've tested the app in a Galaxy S3 Android 4.3 . Map and steam authentication work correctly.

Map has some graphical issue cause WebKit version on old Android is not the newer one but, after all, it work.

**Comment by shardick** [comment]
@maxim-fedotov-1997 would you like to try new version with tablet view? 
Download this: https://www.dropbox.com/s/wnankeb1llypuhc/app-release-tablet.apk?dl=0 

let me know what do you think and how it works on a tablet

**Comment by maxim-fedotov-1997** [comment]
Aww, shucks... Gotta look for emulator of Android... Tablet is back home. XD

**Comment by shardick** [comment]
What a mess :) don't mind, please focus on debugging 4.2.2 issues :)

**Comment by maxim-fedotov-1997** [comment]
Got my hands on Android Studio, guess that'll extend possibilities (like, send project for a debug "build and run")... Since I did found Logcat, but my phone is not rooted yet (although warranty expired XD), which is needed for it.

And wow, works well! I even like how it is done :D
Needs to be done with phone in "album" position, buuuut, I'm being too picky, I think... 
![screenshot_2017-05-28-10-17-47](https://cloud.githubusercontent.com/assets/5875717/26525870/0ebd062c-438f-11e7-804a-d24dd3c8b85a.png)
